#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 13 12:32:03 2019

@author: amitagarwal
"""

import flask
from flask import Flask, request

app = flask.Flask(__name__)

@app.route("/")
def start():
    return "print Hello"

@app.route("/get")
def get_bot_response():
    return "getting response"

@app.route("/postm",methods=(["GET","POST"]))
def post_message():
    method_req = request.method
    print("form :", request.form, request.data)
    return "getting response from post message {}".format(method_req)

if __name__ == "__main__":
    app.run()